name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Clear Java and Gradle options
        run: |
          echo "JAVA_OPTS=" >> "$GITHUB_ENV"
          echo "GRADLE_OPTS=" >> "$GITHUB_ENV"
          echo "JAVA_TOOL_OPTIONS=" >> "$GITHUB_ENV"
          echo "_JAVA_OPTIONS=" >> "$GITHUB_ENV"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: CalcVault-AAB
          path: app/build/outputs/bundle/release/*.aab
